owner: PythonSwiftLink

repository: CythonizeMainPy

swift_version: 5.9

products:
  - library: CythonizeMainPy
    targets:
      - CythonizeMainPy

dependencies:
  - package: PythonCore
    url: https://github.com/PythonSwiftLink/PythonCore
    version:
      upToNextMajor: 311.0.0

targets:
- target: CythonMainPy
  dependencies:
    - product: PythonCore
      package: PythonCore
      
    - binary: output/xcframework

  # linkerSettings:
  #   - framework: Accelerate

      