owner: PythonSwiftLink

repository: CythonizedMainPy

swift_version: 5.8

products:
  - library: CythonizedMainPy
    targets:
      - CythonizedMainPy

dependencies:
  - package: PythonCore
    url: https://github.com/PythonSwiftLink/KivyPythonCore
    version:
      upToNextMajor: 311.0.0

targets:
- target: CythonizedMainPy
  dependencies:
    - product: PythonCore
      package: KivyPythonCore
      
    - binary: output/xcframework

  # linkerSettings:
  #   - framework: Accelerate

      